name: Finale

on: workflow_call

jobs:
  finale:
    runs-on: ubuntu-latest
    name: Final Jobs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: â¤µï¸ Download code coverage results
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: .
          merge-multiple: true

      - name: ğŸ“‹ Display structure of downloaded files
        run: ls -R

      - name: ğŸ“” Generating coverage badges
        uses: jpb06/coverage-badges-action@latest
        if: github.event_name != 'pull_request'
        with:
          branches: main,dev
          commit-message: 'chore: update coverage badges [skip ci]'
          output-folder: ./.github/badges
          coverage-summary-path: |
            ./apps/**/coverage/coverage-summary.json
            ./packages/**/coverage/coverage-summary.json
            ./tooling/**/coverage/coverage-summary.json
            ./tests/**/coverage/coverage-summary.json

      - name: ğŸ“‹ TODO to Issue
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: alstr/todo-to-issue-action@v5.1.7
        with:
          AUTO_ASSIGN: true
